src/BuyHouse/BuyHouse.WEB/Controllers/FlatAdvertController.cs
using AutoMapper;
using BuyHouse.BLL.DTO;
using BuyHouse.BLL.Services.Abstract;
using BuyHouse.DAL.Entities;
using BuyHouse.DAL.Entities.AdvertEntities;
using BuyHouse.WEB.Clients;
using BuyHouse.WEB.Models.AdvertModel;
using BuyHouse.WEB.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System.Security.Claims;
using System.Text.Json;

namespace BuyHouse.WEB.Controllers
{
    public class FlatAdvertController : Controller
    {
        private readonly IAdvertFilterService<FlatAdvert, FlatAdvertFilter> _flatAdvertService;
        private readonly IUserProfileService _userProfileService;
        private readonly BuyHouseAPIClient _client;
        private readonly IPhotosService _photosService;
        private readonly ILikeAdvertService _likeAdvertService;
        private readonly IMapper _mapper;
        private readonly IStringLocalizer<FlatAdvertController> _localizer;

        public FlatAdvertController(IAdvertFilterService<FlatAdvert, FlatAdvertFilter> flatAdertService, 
            IUserProfileService userProfileService,
            IMapper mapper,
            IStringLocalizer<FlatAdvertController> localizer, 
            BuyHouseAPIClient client,
            IPhotosService photosService,
            ILikeAdvertService likeAdvertService)
        {
            _flatAdvertService = flatAdertService;
            _userProfileService = userProfileService;
            _mapper = mapper;
            _localizer = localizer;
            _client = client;
            _photosService = photosService;
            _likeAdvertService = likeAdvertService;
        }

        /// <summary>
        /// CreateAdvert view
        /// </summary>
        /// <returns>View for creating advert</returns>
        [HttpGet]
        [Authorize]
        public IActionResult CreateAdvert() => View();

        /// <summary>
        /// Create flat advert
        /// </summary>
        /// <param name="flatAdvertModel"></param>
        /// <param name="uploads"></param>
        /// <returns>Created advert</returns>
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateAdvertPost(FlatAdvertModel flatAdvertModel, IFormFileCollection uploads)
        {
            if (ModelState.IsValid)
            {
                string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                try
                {
                    FlatAdvert flatAdvert_ = await _client.CreateFlatAdvertAsync(flatAdvertModel, uploads, currentUserId);
                    return RedirectToAction("GetFlatAdvert", new { flatAdvertId = flatAdvert_.Id });
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Error", "Home", new { exception = ex.Message });
                }
            }
            return RedirectToAction("Error", "Home", new { exception = _localizer["Error advert message"] });
        }

        /// <summary>
        /// Search flat adverts
        /// </summary>
        /// <param name="filter"></param>
        /// <param name="pageSize"></param>
        /// <param name="page"></param>
        /// <returns>View with filtered adverts</returns>
        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> Index(FlatAdvertFilter filter, int pageSize, int page = 1)
        {
            try
            {
                ResponseAdvertDTO<FlatAdvert> responseFlatAdvertDTO = await _flatAdvertService
                    .GetAdvertByParametersAsync(filter, pageSize, page);

                string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                var flatAdvertIds = await _likeAdvertService.GetLikedAdvertIdsAsync(currentUserId, TypeOfRealtyAdvert.FlatAdvert);

                var flatAdvertShortModels = _mapper.Map<IEnumerable<FlatAdvert>, List<FlatAdvertShortModel>>(responseFlatAdvertDTO.Adverts);

                IndexFilterViewModel<FlatAdvertShortModel, FlatAdvertFilter> vm = new IndexFilterViewModel<FlatAdvertShortModel, FlatAdvertFilter>()
                {
                    RealtyAdverts = flatAdvertShortModels,
                    RealtyAdvertFilter = filter,
                    PageViewModel = new PageViewModel(responseFlatAdvertDTO.Count, page, responseFlatAdvertDTO.PageSize),
                    LikedAdvert = flatAdvertIds
                };
                return View(vm);
            }
            catch(Exception ex)
            {
                return RedirectToAction("Error", "Home", new { exception = ex.Message });
            }
        }

        /// <summary>
        /// get flat advert with info about user
        /// </summary>
        /// <param name="flatAdvertId"></param>
        /// <returns>View with advert</returns>
        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        [Route("/[controller]/{flatAdvertId:int}")]
        public async Task<IActionResult> GetFlatAdvert(int? flatAdvertId)
        {
            if (flatAdvertId == null)
                return RedirectToAction("Error", "Home");

            try
            {
                FlatAdvertModel flatAdvertModel = new FlatAdvertModel();
                var flatAdvert = await _client.GetFlatAdvertByIDAsync(flatAdvertId);

                var userProfile = await _userProfileService.GetUserProfileInfoAsync(flatAdvert.UserID);

                flatAdvertModel =  _mapper.Map<FlatAdvert, FlatAdvertModel>(flatAdvert);
                GetAdvertViewModel<FlatAdvertModel> vm = new GetAdvertViewModel<FlatAdvertModel>
                {
                    Advert = flatAdvertModel,
                    UserProfile = userProfile
                };
                return View(vm);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { exception = ex.Message });
            }
        }

        /// <summary>
        /// Edit advert
        /// </summary>
        /// <param name="flatAdvertId"></param>
        /// <returns>get view for editing advert</returns>
        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        [Route("/[controller]/[action]/{flatAdvertId:int}")]
        [Authorize]
        public async Task<IActionResult> EditAdvert(int flatAdvertId)
        {
            if (flatAdvertId == null)
                return RedirectToAction("Error", "Home");

            try
            {
                FlatAdvertModel flatAdvertModel = new FlatAdvertModel();
                var flatAdvert = await _client.GetFlatAdvertByIDAsync(flatAdvertId);
                flatAdvertModel = _mapper.Map<FlatAdvert, FlatAdvertModel>(flatAdvert);
                return View(flatAdvertModel);    
            }
            catch(Exception ex)
            {
                return RedirectToAction("Error", "Home", new { exception = ex.Message });
            }
        }

        /// <summary>
        /// edit advert
        /// </summary>
        /// <param name="flatAdvertId"></param>
        /// <param name="flatAdvertModel"></param>
        /// <param name="uploads"></param>
        /// <returns>edited flat advert or error page</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditFlatAdvert(int flatAdvertId, FlatAdvertModel flatAdvertModel, IFormFileCollection uploads)
        {
            if (flatAdvertId == null)
                return RedirectToAction("Error", "Home");

            if (ModelState.IsValid)
            {
                string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                try
                {
                    FlatAdvert flatAdvert_ = await _client.UpdateFlatAdvertAsync(flatAdvertId, flatAdvertModel, uploads, currentUserId);
                    return RedirectToAction("GetFlatAdvert", new { flatAdvertId = flatAdvert_.Id });
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Error", "Home", new { exception = ex.Message });
                }
            }
            return RedirectToAction("Error", "Home", new { exception = _localizer["Error advert message"] });
        }

        /// <summary>
        /// Delete photos from advert
        /// </summary>
        /// <param name="photoId"></param>
        /// <param name="flatAdvertId"></param>
        /// <returns>json with advert and list of photo</returns>
        [Authorize]
        [HttpGet]
        public async Task<JsonResult> DeleteFlatAdvertPhoto(int photoId, int flatAdvertId)
        {
            string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var advert = await _client.GetFlatAdvertByIDAsync(flatAdvertId);
            var flatAdvertModel = _mapper.Map<FlatAdvert, FlatAdvertModel>(advert);
            if (flatAdvertModel.Photos.Count != 1)
            {
                FlatAdvert flatAdvert = await _photosService.DeletePhotoFromFlatAdvertAsync(currentUserId, flatAdvertId, photoId);
                return Json(flatAdvert);
            }
            else
               return Json(advert);
        }

        /// <summary>
        /// Delete flat advert
        /// </summary>
        /// <param name="flatAdvertId"></param>
        /// <returns>View with sellers adverts or error page</returns>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> DeleteFlatAdvert(int flatAdvertId)
        {
            string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            try
            {
                var result = await _client.DeleteFlatAdvertAsync(flatAdvertId, currentUserId);
                if (result != null)
                    return RedirectToAction("GetSellersAdverts", "UserProfile");
                return BadRequest();
            }
            catch (Exception ex)
            {

src/BuyHouse/BuyHouse.WEB/Controllers/HomeController.cs
using AutoMapper;
using BuyHouse.BLL.DTO;
using BuyHouse.BLL.Services.Abstract;
using BuyHouse.DAL.Entities.AdvertEntities;
using BuyHouse.WEB.Models;
using BuyHouse.WEB.Models.AdvertModel;
using BuyHouse.WEB.Models.ViewModels;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BuyHouse.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAdvertFilterService<FlatAdvert, FlatAdvertFilter> _flatAdvertService;
        private readonly IAdvertFilterService<HouseAdvert, HouseAdvertFilter> _houseAdvertFilterService;
        private readonly IAdvertFilterService<RoomAdvert, RoomAdvertFilter> _roomAdvertFilterService;

        private readonly IMapper _mapper;

        public HomeController(IAdvertFilterService<FlatAdvert, FlatAdvertFilter> flatAdvertService, 
            IMapper mapper, 
            IAdvertFilterService<HouseAdvert, HouseAdvertFilter> houseAdvertFilterService,
            IAdvertFilterService<RoomAdvert, RoomAdvertFilter> roomAdvertFilterService)
        {
            _flatAdvertService = flatAdvertService;
            _mapper = mapper;
            _houseAdvertFilterService = houseAdvertFilterService;
            _roomAdvertFilterService = roomAdvertFilterService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                IEnumerable<FlatAdvert> flatAdverts_ = await _flatAdvertService.GetMostLikedAdvertAsync();
                List<FlatAdvertShortModel> flatAdverts = _mapper.Map<IEnumerable<FlatAdvert>, List<FlatAdvertShortModel>>(flatAdverts_);

                IEnumerable<HouseAdvert> houseAdverts_ = await _houseAdvertFilterService.GetMostLikedAdvertAsync();
                List<HouseAdvertShortModel> houseAdverts = _mapper.Map<IEnumerable<HouseAdvert>, List<HouseAdvertShortModel>>(houseAdverts_);

                IEnumerable<RoomAdvert> roomAdverts_ = await _roomAdvertFilterService.GetMostLikedAdvertAsync();
                List<RoomAdvertShortModel> roomAdverts = _mapper.Map<IEnumerable<RoomAdvert>, List<RoomAdvertShortModel>>(roomAdverts_);

                HomeIndexViewModel vm = new HomeIndexViewModel
                {
                    FlatAdverts = flatAdverts,
                    HouseAdverts =houseAdverts,
                    RoomAdverts = roomAdverts
                };
                return View(vm);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { exception = ex.Message });
            }
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(string exception)
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier, ErrorMessage = $"Error message: {exception}" });
        }
    }
}

src/BuyHouse/BuyHouse.WEB/Views/Home/Index.cshtml
@model BuyHouse.WEB.Models.ViewModels.HomeIndexViewModel
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Home</title>
	<link rel="stylesheet" href="~/css/HomeIndex.css" />
</head>
<body>
	<div class="intro">
		<div class="intro_inner">
			<h2 class="title_intro mb-5">@Localizer["Intro title"]</h2>
			<a class="btn btn-lg btn-warning btn_intro" asp-action="Index" asp-controller="FlatAdvert">@Localizer["Apartments"]</a>
			<a class="btn btn-lg btn-warning btn_intro" asp-action="Index" asp-controller="HouseAdvert">@Localizer["Houses"]</a>
			<a class="btn btn-lg btn-warning btn_intro" asp-action="Index" asp-controller="RoomAdvert">@Localizer["Rooms"]</a>
		</div>
	</div>

	<div class="container">
		<div class="row mb-4">
			<h2 class="title_block_advert mt-3">@Localizer["Apartment advert title"] <img src="~/images/icons/flat.png" width="50" height="50" /></h2>
			<hr />
		</div>
	</div>

	<div class="container">
		<div class="row row_block_advert">
			@foreach (var item in Model.FlatAdverts)
			{
				<div class="col-md-4 col-sm-12 col-xs-12 grow">
					<a class="link_block_advert" asp-action="GetFlatAdvert" asp-controller="FlatAdvert" asp-route-flatAdvertId="@item.Id">
						<img class="img-responsive img_block_advert" src="@item.Photos.FirstOrDefault().Path">
						<div class="mt-3 info_block_advert col-md-12">
							<p class="param_block_advert">
								<img src="~/images/icons/money.png" class="mb-2" width="20" height="20" />
								<b>@item.TotalPrice @item.Currency</b>
								@Localizer["Price per object"]
								(@item.PricePerSquareMeter @item.Currency @Localizer["Per"] м<sup>2</sup>)
							</p>
							<h5>@item.MainInfo.City, @item.MainInfo.Street, @item.MainInfo.HouseNumber</h5>
							<p class="param_block_advert">
								<b>@Localizer["Total area"]:</b> @item.TotalArea м<sup>2</sup><br>
								<b>@Localizer["Rooms"]:</b> @item.Rooms
							</p>
						</div>
					</a>
				</div>
			}
		</div>
	</div>

	<div class="SaleBuy_block">
		<h2 class="title_block_SaleBuy">@Localizer["SALE or BUY your real estate!"]</h2>
	</div>

	<div class="container">
		<div class="row mb-4">
			<h2 class="title_block_advert mt-3">@Localizer["House advert title"] <img src="~/images/icons/home.png" width="50" height="50" /></h2>
			<hr />
		</div>
	</div>

	<div class="container">
		<div class="row row_block_advert">
			@foreach (var item in Model.HouseAdverts)
			{
				<div class="col-md-4 col-sm-12 col-xs-12 grow">
					<a class="link_block_advert" asp-action="GetHouseAdvert" asp-controller="HouseAdvert" asp-route-houseAdvertId="@item.Id">
						<img class="img-responsive img_block_advert" src="@item.Photos.FirstOrDefault().Path">
						<div class="mt-3 info_block_advert col-md-12">
							<p class="param_block_advert">
								<img src="~/images/icons/money.png" class="mb-2" width="20" height="20" />
								<b>@item.TotalPrice @item.Currency</b>
								@Localizer["Price per object"]
								(@item.PricePerSquareMeter @item.Currency @Localizer["Per"] м<sup>2</sup>)
							</p>
							<h5>@item.MainInfo.City, @item.MainInfo.Street, @item.MainInfo.HouseNumber</h5>
							<p class="param_block_advert">
								<b>@Localizer["Total area"]:</b> @item.TotalArea м<sup>2</sup><br>
								<b>@Localizer["land area"]:</b> @item.TotalArea м<sup>2</sup><br>
								<b>@Localizer["Rooms"]:</b> @item.Rooms
							</p>
						</div>
					</a>
				</div>
			}
		</div>
	</div>

	<div class="ForUser_block row grow">
		<div class="col-lg-4"><img src="https://cdn-icons-png.flaticon.com/512/1029/1029023.png" class="info_img"></div>
		<div class="col-lg-4"><img src="https://cdn-icons-png.flaticon.com/512/2544/2544336.png" class="info_img"></div>
		<div class="col-lg-4"><img src="https://cdn-icons-png.flaticon.com/512/3211/3211596.png" class="info_img"></div>
	</div>


	<div class="container">
		<div class="row mb-4">
			<h2 class="title_block_advert mt-3">@Localizer["Room advert title"] <img src="~/images/icons/room.png" width="50" height="50" /></h2>
			<hr />
		</div>
	</div>

	<div class="container">
		<div class="row row_block_advert">
			@foreach (var item in Model.RoomAdverts)
			{
				<div class="col-md-4 col-sm-12 col-xs-12 grow">
					<a class="link_block_advert" asp-action="GetRoomAdvert" asp-controller="RoomAdvert" asp-route-roomAdvertId="@item.Id">
						<img class="img-responsive img_block_advert" src="@item.Photos.FirstOrDefault().Path">
						<div class="mt-3 info_block_advert col-md-12">
							<p class="param_block_advert">
								<img src="~/images/icons/money.png" class="mb-2" width="20" height="20" />
								<b>@item.TotalPrice @item.Currency</b>
								@Localizer["Price per object"]
								(@item.PricePerSquareMeter @item.Currency @Localizer["Per"] м<sup>2</sup>)
							</p>
							<h5>@item.MainInfo.City, @item.MainInfo.Street, @item.MainInfo.HouseNumber</h5>
							<p class="param_block_advert">
								<b>@Localizer["Total area"]:</b> @item.TotalArea м<sup>2</sup><br>
								<b>@Localizer["Rooms"]:</b> 1
							</p>
						</div>
					</a>
				</div>
			}
		</div>
	</div>
</body>
</html>