src/BuyHouse/BuyHouse.WEB/Controllers/RoomAdvertController.cs
using AutoMapper;
using BuyHouse.BLL.DTO;
using BuyHouse.BLL.Services.Abstract;
using BuyHouse.DAL.Entities;
using BuyHouse.DAL.Entities.AdvertEntities;
using BuyHouse.WEB.Clients;
using BuyHouse.WEB.Models.AdvertModel;
using BuyHouse.WEB.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System.Security.Claims;

namespace BuyHouse.WEB.Controllers
{
    public class RoomAdvertController : Controller
    {
        private readonly BuyHouseAPIClient _client;
        private readonly IStringLocalizer<RoomAdvertController> _localizer;
        private readonly IMapper _mapper;
        private readonly IUserProfileService _userProfileService;
        private readonly IAdvertFilterService<RoomAdvert, RoomAdvertFilter> _roomAdvertFilterService;
        private readonly IPhotosService _photosService;
        private readonly ILikeAdvertService _likeAdvertService;

        public RoomAdvertController(BuyHouseAPIClient client,
            IStringLocalizer<RoomAdvertController> localizer,
            IMapper mapper,
            IUserProfileService userProfileService,
            IAdvertFilterService<RoomAdvert, RoomAdvertFilter> roomAdvertFilterService,
            IPhotosService photosService,
            ILikeAdvertService likeAdvertService)
        {
            _client = client;
            _localizer = localizer;
            _mapper = mapper;
            _userProfileService = userProfileService;
            _roomAdvertFilterService = roomAdvertFilterService;
            _photosService = photosService;
            _likeAdvertService = likeAdvertService;
        }

        /// <summary>
        /// Get view for creating advert
        /// </summary>
        /// <returns>View for creating</returns>
        [HttpGet]
        [Authorize]
        public IActionResult CreateAdvert() => View();

        /// <summary>
        /// Create room advert
        /// </summary>
        /// <param name="roomAdvert"></param>
        /// <param name="uploads"></param>
        /// <returns>Created room advert</returns>
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateAdvertPost(RoomAdvertModel roomAdvert, IFormFileCollection uploads)
        {
            if (ModelState.IsValid)
            {
                string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                try
                {
                    RoomAdvert roomAdvert_ = await _client.CreateRoomAdvertAsync(roomAdvert, uploads, currentUserId);
                    return RedirectToAction("GetRoomAdvert", new { roomAdvertId = roomAdvert_.Id });
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Error", "Home", new { exception = ex.Message });
                }
            }
            return RedirectToAction("Error", "Home", new { exception = _localizer["Error advert message"] });
        }

        /// <summary>
        /// Get info about room 
        /// </summary>
        /// <param name="roomAdvertId"></param>
        /// <returns>Room advert</returns>
        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        [Route("/[controller]/{roomAdvertId:int}")]
        public async Task<IActionResult> GetRoomAdvert(int roomAdvertId)
        {
            if (roomAdvertId == null)
                return RedirectToAction("Error", "Home");

            try
            {
                RoomAdvertModel roomAdvertModel = new RoomAdvertModel();
                var roomAdvert = await _client.GetRoomAdvertByIdAsync(roomAdvertId);

                var userProfile = await _userProfileService.GetUserProfileInfoAsync(roomAdvert.UserID);

                roomAdvertModel = _mapper.Map<RoomAdvert, RoomAdvertModel>(roomAdvert);
                GetAdvertViewModel<RoomAdvertModel> vm = new GetAdvertViewModel<RoomAdvertModel>
                {
                    Advert = roomAdvertModel,
                    UserProfile = userProfile
                };
                return View(vm);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { exception = ex.Message });
            }
        }

        /// <summary>
        /// Search room adverts
        /// </summary>
        /// <param name="filter"></param>
        /// <param name="pageSize"></param>
        /// <param name="page"></param>
        /// <returns>View with filtered adverts</returns>
        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> Index(RoomAdvertFilter filter, int pageSize, int page = 1)
        {
            try
            {
                string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                ResponseAdvertDTO<RoomAdvert> responseRoomAdvertDTO = await _roomAdvertFilterService
                    .GetAdvertByParametersAsync(filter, pageSize, page);

                var roomAdvertIds = await _likeAdvertService.GetLikedAdvertIdsAsync(currentUserId, TypeOfRealtyAdvert.RoomAdvert);

                var roomAdvertShortModels = _mapper.Map<IEnumerable<RoomAdvert>, List<RoomAdvertShortModel>>(responseRoomAdvertDTO.Adverts);

                IndexFilterViewModel<RoomAdvertShortModel, RoomAdvertFilter> vm = new IndexFilterViewModel<RoomAdvertShortModel, RoomAdvertFilter>()
                {
                    RealtyAdverts = roomAdvertShortModels,
                    RealtyAdvertFilter = filter,
                    PageViewModel = new PageViewModel(responseRoomAdvertDTO.Count, page, responseRoomAdvertDTO.PageSize),
                    LikedAdvert = roomAdvertIds
                };
                return View(vm);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { exception = ex.Message });
            }
        }

        /// <summary>
        /// Edit advert
        /// </summary>
        /// <param name="roomAdvertId"></param>
        /// <returns>get view for editing advert</returns>
        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        [Route("/[controller]/[action]/{roomAdvertId:int}")]
        [Authorize]
        public async Task<IActionResult> EditAdvert(int roomAdvertId)
        {
            if (roomAdvertId == null)
                return RedirectToAction("Error", "Home");

            try
            {
                RoomAdvertModel roomAdvertModel = new RoomAdvertModel();
                var roomAdvert = await _client.GetRoomAdvertByIdAsync(roomAdvertId);
                roomAdvertModel = _mapper.Map<RoomAdvert, RoomAdvertModel>(roomAdvert);
                return View(roomAdvertModel);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { exception = ex.Message });
            }
        }

        /// <summary>
        /// edit advert
        /// </summary>
        /// <param name="roomAdvertId"></param>
        /// <param name="roomAdvertModel"></param>
        /// <param name="uploads"></param>
        /// <returns>edited room advert or error page</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditRoomAdvert(int roomAdvertId, RoomAdvertModel roomAdvertModel, IFormFileCollection uploads)
        {
            if (roomAdvertId == null)
                return RedirectToAction("Error", "Home");

            if (ModelState.IsValid)
            {
                string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value; ;
                try
                {
                    RoomAdvert roomAdvert_ = await _client.UpdateRoomAdvertAsync(roomAdvertId, roomAdvertModel, uploads, currentUserId);
                    return RedirectToAction("GetRoomAdvert", new { roomAdvertId = roomAdvert_.Id });
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Error", "Home", new { exception = ex.Message });
                }
            }
            return RedirectToAction("Error", "Home", new { exception = _localizer["Error advert message"] });
        }

        /// <summary>
        /// Delete photos from advert
        /// </summary>
        /// <param name="photoId"></param>
        /// <param name="roomAdvertId"></param>
        /// <returns>json with advert and list of photo</returns>
        [Authorize]
        [HttpGet]
        public async Task<JsonResult> DeleteRoomAdvertPhoto(int photoId, int roomAdvertId)
        {
            string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var advert = await _client.GetRoomAdvertByIdAsync(roomAdvertId);
            var roomAdvertModel = _mapper.Map<RoomAdvert, RoomAdvertModel>(advert);
            if (roomAdvertModel.Photos.Count != 1)
            {
                RoomAdvert roomAdvert = await _photosService.DeletePhotoFromRoomAdvertAsync(currentUserId, roomAdvertId, photoId);
                return Json(roomAdvert);
            }
            else
                return Json(advert);
        }

        /// <summary>
        /// Delete room advert
        /// </summary>
        /// <param name="roomAdvertId"></param>
        /// <returns>View with sellers adverts or error page</returns>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> DeleteRoomAdvert(int roomAdvertId)
        {
            string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            try
            {
                var result = await _client.DeleteRoomAdvertAsync(roomAdvertId, currentUserId);
                if (result != null)
                    return RedirectToAction("GetSellersAdverts", "UserProfile");
                return BadRequest();
            }
            catch (Exception ex)
            {

src/BuyHouse/BuyHouse.WEB/Views/RoomAdvert/CreateAdvert.cshtml
@model BuyHouse.WEB.Models.AdvertModel.RoomAdvertModel
@using BuyHouse.DAL.Entities.HelperEnum
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Search</title>
	<link rel="stylesheet" href="~/css/Create-EditAdvert.css" />
</head>
<body>
	<div class="container pt-3 pb-3">
		<div class="row">
			<h1 class="main_title">@Localizer["Create your advert"]: </h1><hr />
			<div class="col-lg-7 col-12 col-xs-12 col-md-12 order-md-2 order-2 order-lg-1 form_block">
				<form method="post" asp-action="CreateAdvertPost" asp-controller="RoomAdvert" enctype="multipart/form-data">
					<h2 class="subtitle">@Localizer["MainInfo"]</h2>
					@Html.LabelFor(m => m.MainInfo.Region, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.MainInfo.Region, new { @class = "form-control input_text", required="true"})
					@Html.ValidationMessageFor(m => m.MainInfo.Region,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.MainInfo.City, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.MainInfo.City, new { @class = "form-control", @required="true"  })
					@Html.ValidationMessageFor(m => m.MainInfo.City,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.MainInfo.Street, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.MainInfo.Street, new { @class = "form-control", @required="true"  })
					@Html.ValidationMessageFor(m => m.MainInfo.Street,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.MainInfo.HouseNumber, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.MainInfo.HouseNumber, new { @class = "form-control", @required="true"  })
					@Html.ValidationMessageFor(m => m.MainInfo.HouseNumber,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.MainInfo.FlatNumber, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.MainInfo.FlatNumber, new { @class = "form-control", @type="number", @required="true"  })
					@Html.ValidationMessageFor(m => m.MainInfo.FlatNumber,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.MainInfo.RegistrationDate, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.MainInfo.RegistrationDate, new { @class = "form-control", @type="date", @required="true"  })
					@Html.ValidationMessageFor(m => m.MainInfo.RegistrationDate,"", new{@class="validation_text"})<br />
					<hr />

					<h2 class="subtitle">@Localizer["Parameters"]</h2>
					@Html.LabelFor(m => m.Description, new{@class="input_lable"})
					@Html.TextAreaFor(m => m.Description, new { @class = "form-control", @required="true"  })
					@Html.ValidationMessageFor(m => m.Description,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.Type, new{@class="input_lable"})<br />
					@Html.RadioButtonFor(m => m.Type, TypeOfRealty.Primary , new{ @required="true", @class="radio_input"})
					<lable>@Localizer["Primary"]</lable><br />
					@Html.RadioButtonFor(m => m.Type, TypeOfRealty.Secondary , new{ @required="true", @class="radio_input"})
					<lable>@Localizer["Secondary"]</lable><br />
					@Html.ValidationMessageFor(m => m.Type,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.TotalArea, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.TotalArea, new { @class = "form-control", @required="true" })
					@Html.ValidationMessageFor(m => m.TotalArea,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.LivingArea, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.LivingArea, new { @class = "form-control", @required="true" })
					@Html.ValidationMessageFor(m => m.LivingArea,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.Floor, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.Floor, new { @class = "form-control", @type="number", @required="true"})
					@Html.ValidationMessageFor(m => m.Floor,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.TotalCountFloors, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.TotalCountFloors, new { @class = "form-control", @type="number", @required="true" })
					@Html.ValidationMessageFor(m => m.TotalCountFloors,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.Heating, new{@class="input_lable"})<br />
					@Html.RadioButtonFor(m => m.Heating,@TypeOfHeating.Centralized, new{ @required="true", @class="radio_input"})
					<lable>@Localizer["Centralized"]</lable><br />
					@Html.RadioButtonFor(m => m.Heating,@TypeOfHeating.Individual, new{ @required="true", @class="radio_input"})
					<lable>@Localizer["Individual"]</lable><br />
					@Html.RadioButtonFor(m => m.Heating,@TypeOfHeating.Сombined, new{ @required="true", @class="radio_input"})
					<lable>@Localizer["Сombined"]</lable><br />
					@Html.RadioButtonFor(m => m.Heating,@TypeOfHeating.WithoutHeating, new{ @required="true", @class="radio_input"})
					<lable>@Localizer["WithoutHeating"]</lable><br />
					@Html.ValidationMessageFor(m => m.Heating,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.RegistrationNumber, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.RegistrationNumber, new { @class = "form-control", @required="true"})
					@Html.ValidationMessageFor(m => m.RegistrationNumber,"", new{@class="validation_text"})<br />

					<div class="row">
						<div class="col-md-10">
							<lable class="input_lable">@Localizer["Price"]</lable>
							@Html.TextBoxFor(m => m.TotalPrice, new { @class = "form-control", @type="number", required="true" })
							@Html.ValidationMessageFor(m => m.TotalPrice,"", new{@class="validation_text"})<br />
						</div>
						<div class="col-md-2 mt-1">
							<lable class="input_lable">Валюта</lable>
							<select class="form-control" name="Currency" required>
								<option value="@Currency.USD">USD</option>
								<option value="@Currency.Euro">Euro</option>
								<option value="@Currency.UAH">UAH</option>
							</select>
							@Html.ValidationMessageFor(m => m.Currency,"", new{@class="validation_text"})<br />
						</div>
					</div>

					@Html.LabelFor(m => m.TypePrice, new{@class="input_lable"})<br />
					@Html.RadioButtonFor(m => m.TypePrice, TypeOfPrice.PerSquareMeter , new{ @required="true", @class="radio_input"})
					<lable>@Localizer["PricePerSquareMeter"]</lable><br />
					@Html.RadioButtonFor(m => m.TypePrice, TypeOfPrice.TotalPrice , new{ @required="true", @class="radio_input"})
					<lable>@Localizer["PricePerObject"]</lable><br />
					@Html.ValidationMessageFor(m => m.TypePrice,"", new{@class="validation_text"})<br />

					<hr />
					<h2 class="subtitle">@Localizer["Photo"]</h2>
					<p>@Localizer["Upload photos message"]</p>
					<input class="form-control" type="file" multiple name="uploads" required accept="image/jpeg,image/png" /><br>
					@Html.ValidationMessageFor(m => m.Photos,"", new{@class="validation_text"})<br />
					<button type="submit" class="btn btn-lg btn-dark">@Localizer["Create advert"]</button>
				</form>
			</div>
			<div class="col-lg-4 img_block col-md-12 order-lg-2 order-md-1 order-1 ">
			</div>
		</div>
	</div>
</body>
</html>

src/BuyHouse/BuyHouse.WEB/Views/RoomAdvert/Index.cshtml
@model BuyHouse.WEB.Models.ViewModels.IndexFilterViewModel<RoomAdvertShortModel, RoomAdvertFilter>
@using BuyHouse.BLL.DTO
@using BuyHouse.DAL.Entities.HelperEnum
@using BuyHouse.WEB.Models.AdvertModel
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@addTagHelper *, BuyHouse.WEB
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Search</title>
	<link rel="stylesheet" href="~/css/IndexAdvert.css" />
</head>
<body>
	<div class="container">
		<form name="filterForm" method="post" asp-action="Index" asp-controller="RoomAdvert">
			<div class="row mt-3 blue_block">
				<div class="col-lg-5 col-md-12 order-1 oreder-md-2">
					<label>@Localizer["label pageSize"]: </label><br />
					<div class="radio-toolbar">
						<input class="pageSize" type="radio" id="size10" name="pageSize" value="10">
						<label for="size10">10</label>
						<input class="pageSize" type="radio" id="size20" name="pageSize" value="20">
						<label for="size20">20</label>
						<input class="pageSize" type="radio" id="size50" name="pageSize" value="50">
						<label for="size50">50</label>
					</div>

					<label>@Localizer["total area"]: </label><br />
					<div class="flex_div">
						<label class="m-2">@Localizer["from"]: </label>
						<input name="filter.MinTotalArea" id="inputMinMaxValue" value="@Model.RealtyAdvertFilter.MinTotalArea" class="form-control from-to-input">
						<label class="m-2">@Localizer["to"]: </label>
						<input name="filter.MaxTotalArea" id="inputMinMaxValue" value="@Model.RealtyAdvertFilter.MaxTotalArea" class="form-control from-to-input">
					</div>
					<label>@Localizer["floor"]: </label><br />
					<div class="flex_div">
						<label class="m-2">@Localizer["from"]: </label>
						<input name="filter.MinFloor" id="inputMinMaxValue" value="@Model.RealtyAdvertFilter.MinFloor" class="form-control from-to-input" />
						<label class="m-2">@Localizer["to"]: </label>
						<input name="filter.MaxFloor" id="inputMinMaxValue" value="@Model.RealtyAdvertFilter.MaxFloor" class="form-control from-to-input" />
					</div>
				</div>
				<div class="col-lg-6 col-md-12 order-md-1 oreder-2 col2_filter">
					<label>@Localizer["city"]: </label>
					<input name="filter.CityName" value="@Model.RealtyAdvertFilter.CityName" class="form-control" />

					<div class="row mt-2">
						<label>@Localizer["price"]: </label><br />
						<div class="col-lg-4 col-md-12 col_price">
							<label class="price_lable">@Localizer["from"]: </label>
							<input id="inputMinMaxValue" name="filter.MinPrice" class="form-control from-to-input" value="@Model.RealtyAdvertFilter.MinPrice" />
							<label class="price_lable">@Localizer["to"]: </label>
							<input id="inputMinMaxValue" name="filter.MaxPrice" class="form-control from-to-input" value="@Model.RealtyAdvertFilter.MaxPrice" />
						</div>
						<div class="col-lg-4 col-md-12">
							<label class="control-label">@Localizer["currency"]: </label><br />
							<div class="radio-toolbar">
								<input class="currency" type="radio" id="Any" name="filter.Currency" value="@Currency.Any">
								<label for="Any" class="currency_lable mt-2">@Localizer["any"]</label>
								<input class="currency" type="radio" id="USD" name="filter.Currency" value="@Currency.USD">
								<label for="USD" class="currency_lable mt-2">@Localizer["USD full name"]</label>
								<input class="currency" type="radio" id="Euro" name="filter.Currency" value="@Currency.Euro">
								<label for="Euro" class="currency_lable mt-2">@Localizer["Euro full name"]</label>
								<input class="currency" type="radio" id="UAH" name="filter.Currency" value="@Currency.UAH">
								<label for="UAH" class="currency_lable mt-2">@Localizer["UAH full name"]</label>
							</div>
						</div>
						<div class="col-lg-4 col-md-12">
							<label class="control-label">@Localizer["price per"]: </label><br />
							<div class="radio-toolbar">
								<input class="typeOfPrice" type="radio" id="TotalPrice" name="filter.TypeOfPrice" value="@TypeOfPrice.TotalPrice">
								<label for="TotalPrice" class="mt-2 typePrice_lable">@Localizer["per object"]</label>
								<input class="typeOfPrice" type="radio" id="PerSquareMeter" name="filter.TypeOfPrice" value="@TypeOfPrice.PerSquareMeter">
								<label for="PerSquareMeter" class="mt-2 typePrice_lable">@Localizer["per square meter"]</label>
							</div>
						</div>
					</div>
				</div>
				<input type="submit" value="@Localizer["filter"]" class="btn btn_submitform btn-lg mt-2 mb-2 order-3" />
			</div>
		</form>

		@foreach (var item in Model.RealtyAdverts)
		{
			<div class="row mt-5 grow">
				<div class="col-lg-3 photos_block col-md-12">
					<img src="@item.Photos.FirstOrDefault().Path" class="big_flatimg">
					<div class="small_photos">
						@{
							int ind = 1;
						}
						@foreach (var photo in item.Photos)
						{
							ind++;
							if (@item.Photos.FirstOrDefault().Path == photo.Path)
								continue;
							<img src="@photo.Path" class="small_flatimg">
							if (ind >= 5)
								break;
						}
					</div>
				</div>
				<div class="col-lg-8 col-md-12">
					<p class="param_block_advert">
						<img src="~/images/icons/money.png" class="mb-2" width="20" height="20" />
						<span id="totalPrice">@item.TotalPrice</span> @Localizer[item.Currency.ToString()]
						@Localizer["price"] @Localizer["per object"]
						(<span id="pricePerSquareMeter">@item.PricePerSquareMeter</span> @Localizer[item.Currency.ToString()] @Localizer["per"] м<sup>2</sup>)
					</p>
					<h3>@item.MainInfo.City, @item.MainInfo.Street, @item.MainInfo.HouseNumber</h3>
					<p class="info_block">
						<b>@Localizer["total area"]:</b> @item.TotalArea м<sup>2</sup><br>
						<b>@Localizer["floor"]:</b> @item.Floor @Localizer["out of"] @item.TotalCountFloors
					<p class="description">@Html.Raw(item.Description)</p>
					<hr>
					<div class="row">
						<div class="col-md-11">
							<p>@item.CreationDate.Value.ToString("yyyy-MM-dd")</p>
						</div>
						<div class="col-md-1 like_block">
							@if (User.Identity.IsAuthenticated)
								{
									@if (Model.LikedAdvert.Any(x => x == item.Id))
									{
										<a class="btn-like-advert" data-flatAdvertId="@item.Id"><img id="likeimg" src="https://cdn-icons-png.flaticon.com/512/2589/2589175.png" width="40" height="40"></a>
									}
									else
									{
										<a class="btn-like-advert" data-flatAdvertId="@item.Id"><img id="likeimg" src="https://cdn-icons-png.flaticon.com/512/2589/2589197.png" width="40" height="40"></a>
									}
								
								<div id="like_advert" class="like_count">@item.LikeCount</div>
								}
						</div>
					</div>
					<a class="btn btn-dark btn-md datails_btn" href="~/RoomAdvert/@item.Id">@Localizer["Details"]</a>
				</div>
			</div>
		}

		<page-link class="mt-2" page-model="Model.PageViewModel" page-action="Index"
				   page-url-filter.CityName="@Model.RealtyAdvertFilter.CityName"
				   page-url-filter.MinPrice="@Model.RealtyAdvertFilter.MinPrice"
				   page-url-filter.MaxPrice="@Model.RealtyAdvertFilter.MaxPrice"
				   page-url-filter.TypeOfPrice="@Model.RealtyAdvertFilter.TypeOfPrice"
				   page-url-filter.Currency="@Model.RealtyAdvertFilter.Currency"
				   page-url-filter.MinTotalArea="@Model.RealtyAdvertFilter.MinTotalArea"
				   page-url-filter.MaxTotalArea="@Model.RealtyAdvertFilter.MaxTotalArea"
				   page-url-filter.MinFloor="@Model.RealtyAdvertFilter.MinFloor"
				   page-url-filter.MaxFloor="@Model.RealtyAdvertFilter.MaxFloor"
				   page-url-pageSize="@Model.PageViewModel.PageSize">
		</page-link>
	</div>
	<script src="~/js/FilterScript.js"></script>
	@section Scripts{<script src="~/js/LikeAdvertScript.js"></script>
		<script>
			const urlRoomAdvert = 'RoomAdvert/LikeRoomAdvert/?roomAdvertId='
			LikeAdvert(urlRoomAdvert);
		</script>
	}
</body>
</html>