src/BuyHouse/BuyHouse.WEB/Models/ViewModels/GetHouseAdvertViewModel.cs
using BuyHouse.BLL.DTO;
using BuyHouse.WEB.Models.AdvertModel;

namespace BuyHouse.WEB.Models.ViewModels
{
    public class GetHouseAdvertViewModel
    {
        public HouseAdvertModel? HouseAdvert { get; set; }
        public UserProfileDTO? UserProfile { get; set; }
    }
}

src/BuyHouse/BuyHouse.WEB/Controllers/HouseAdvertController.cs
using AutoMapper;
using BuyHouse.BLL.DTO;
using BuyHouse.BLL.Services.Abstract;
using BuyHouse.DAL.Entities;
using BuyHouse.DAL.Entities.AdvertEntities;
using BuyHouse.WEB.Clients;
using BuyHouse.WEB.Models.AdvertModel;
using BuyHouse.WEB.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System.Security.Claims;

namespace BuyHouse.WEB.Controllers
{
    public class HouseAdvertController : Controller
    {
        private readonly BuyHouseAPIClient _client;
        private readonly IStringLocalizer<HouseAdvertController> _localizer;
        private readonly IMapper _mapper;
        private readonly IUserProfileService _userProfileService;
        private readonly IAdvertFilterService<HouseAdvert, HouseAdvertFilter> _houseAdvertFilterService;
        private readonly IPhotosService _photosService;
        private readonly ILikeAdvertService _likeAdvertService;

        public HouseAdvertController(BuyHouseAPIClient client, 
            IStringLocalizer<HouseAdvertController> localizer,
            IMapper mapper,
            IUserProfileService userProfileService,
            IAdvertFilterService<HouseAdvert, HouseAdvertFilter> houseAdvertFilterService,
            IPhotosService photosService,
            ILikeAdvertService likeAdvertService)
        {
            _client = client;
            _localizer = localizer;
            _mapper = mapper;
            _userProfileService = userProfileService;
            _houseAdvertFilterService = houseAdvertFilterService;
            _photosService = photosService;
            _likeAdvertService = likeAdvertService;
        }

        /// <summary>
        /// Get view for creating advert
        /// </summary>
        /// <returns>View for creating</returns>
        [HttpGet]
        [Authorize]
        public IActionResult CreateAdvert() => View();

        /// <summary>
        /// Create house advert
        /// </summary>
        /// <param name="houseAdvert"></param>
        /// <param name="uploads"></param>
        /// <returns>Created house advert</returns>
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateAdvertPost(HouseAdvertModel houseAdvert, IFormFileCollection uploads)
        {
            if (ModelState.IsValid)
            {
                string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                try
                {
                    HouseAdvert houseAdvert_ = await _client.CreateHouseAdvertAsync(houseAdvert, uploads, currentUserId);
                    return RedirectToAction("GetHouseAdvert", new { houseAdvertId = houseAdvert_.Id });
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Error", "Home", new { exception = ex.Message });
                }
            }
            return RedirectToAction("Error", "Home", new { exception = _localizer["Error advert message"] });
        }

        /// <summary>
        /// Get info about house
        /// </summary>
        /// <param name="houseAdvertId"></param>
        /// <returns>House advert</returns>
        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        [Route("/[controller]/{houseAdvertId:int}")]
        public async Task<IActionResult> GetHouseAdvert(int houseAdvertId)
        {
            if (houseAdvertId == null)
                return RedirectToAction("Error", "Home");

            try
            {
                HouseAdvertModel houseAdvertModel = new HouseAdvertModel();
                var houseAdvert = await _client.GetHouseAdvertByIdAsync(houseAdvertId);

                var userProfile = await _userProfileService.GetUserProfileInfoAsync(houseAdvert.UserID);

                houseAdvertModel = _mapper.Map<HouseAdvert, HouseAdvertModel>(houseAdvert);
                GetAdvertViewModel<HouseAdvertModel> vm = new GetAdvertViewModel<HouseAdvertModel>
                {
                    Advert = houseAdvertModel,
                    UserProfile = userProfile
                };
                return View(vm);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { exception = ex.Message });
            }
        }

        /// <summary>
        /// Serch page for house advert
        /// </summary>
        /// <param name="filter"></param>
        /// <param name="pageSize"></param>
        /// <param name="page"></param>
        /// <returns>House adverts by parameters</returns>
        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> Index(HouseAdvertFilter filter, int pageSize, int page = 1)
        {
            try
            {
                string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                ResponseAdvertDTO<HouseAdvert> responseHouseAdvertDTO = await _houseAdvertFilterService
                    .GetAdvertByParametersAsync(filter, pageSize, page);

                var houseAdvertIds = await _likeAdvertService.GetLikedAdvertIdsAsync(currentUserId, TypeOfRealtyAdvert.HouseAdvert);

                var houseAdvertShortModels = _mapper.Map<IEnumerable<HouseAdvert>, List<HouseAdvertShortModel>>(responseHouseAdvertDTO.Adverts);

                IndexFilterViewModel<HouseAdvertShortModel, HouseAdvertFilter> vm = new IndexFilterViewModel<HouseAdvertShortModel, HouseAdvertFilter>()
                {
                    RealtyAdverts = houseAdvertShortModels,
                    RealtyAdvertFilter = filter,
                    PageViewModel = new PageViewModel(responseHouseAdvertDTO.Count, page, responseHouseAdvertDTO.PageSize),
                    LikedAdvert = houseAdvertIds
                };
                return View(vm);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { exception = ex.Message });
            }
        }

        /// <summary>
        /// Edit advert
        /// </summary>
        /// <param name="houseAdvertId"></param>
        /// <returns>get view for editing advert</returns>
        [HttpGet]
        [ApiExplorerSettings(IgnoreApi = true)]
        [Route("/[controller]/[action]/{houseAdvertId:int}")]
        [Authorize]
        public async Task<IActionResult> EditAdvert(int houseAdvertId)
        {
            if (houseAdvertId == null)
                return RedirectToAction("Error", "Home");

            try
            {
                HouseAdvertModel houseAdvertModel = new HouseAdvertModel();
                var houseAdvert = await _client.GetHouseAdvertByIdAsync(houseAdvertId);
                houseAdvertModel = _mapper.Map<HouseAdvert, HouseAdvertModel>(houseAdvert);
                return View(houseAdvertModel);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new { exception = ex.Message });
            }
        }

        /// <summary>
        /// edit advert
        /// </summary>
        /// <param name="houseAdvertId"></param>
        /// <param name="houseAdvertModel"></param>
        /// <param name="uploads"></param>
        /// <returns>edited house advert or error page</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditHouseAdvert(int houseAdvertId, HouseAdvertModel houseAdvertModel, IFormFileCollection uploads)
        {
            if (houseAdvertId == null)
                return RedirectToAction("Error", "Home");

            if (ModelState.IsValid)
            {
                string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                try
                {
                    HouseAdvert houseAdvert_ = await _client.UpdateHouseAdvertAsync(houseAdvertId, houseAdvertModel, uploads, currentUserId);
                    return RedirectToAction("GetHouseAdvert", new { houseAdvertId = houseAdvert_.Id });
                }
                catch (Exception ex)
                {
                    return RedirectToAction("Error", "Home", new { exception = ex.Message });
                }
            }
            return RedirectToAction("Error", "Home", new { exception = _localizer["Error advert message"] });
        }

        /// <summary>
        /// Delete photos from advert
        /// </summary>
        /// <param name="photoId"></param>
        /// <param name="flatAdvertId"></param>
        /// <returns>json with advert and list of photo</returns>
        [Authorize]
        [HttpGet]
        public async Task<JsonResult> DeleteHouseAdvertPhoto(int photoId, int houseAdvertId)
        {
            string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var advert = await _client.GetHouseAdvertByIdAsync(houseAdvertId);
            var houseAdvertModel = _mapper.Map<HouseAdvert, HouseAdvertModel>(advert);
            if (houseAdvertModel.Photos.Count != 1)
            {
                HouseAdvert flatAdvert = await _photosService.DeletePhotoFromHouseAdvertAsync(currentUserId, houseAdvertId, photoId);
                return Json(flatAdvert);
            }
            else
                return Json(advert);
        }

        /// <summary>
        /// Delete house advert
        /// </summary>
        /// <param name="houseAdvertId"></param>
        /// <returns>View with sellers adverts or error page</returns>
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> DeleteHouseAdvert(int houseAdvertId)
        {
            string? currentUserId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            try
            {
                var result = await _client.DeleteHouseAdvertAsync(houseAdvertId, currentUserId);
                if (result != null)
                    return RedirectToAction("GetSellersAdverts", "UserProfile");
                return BadRequest();

src/BuyHouse/BuyHouse.WEB/Views/HouseAdvert/CreateAdvert.cshtml
@model BuyHouse.WEB.Models.AdvertModel.HouseAdvertModel
@using BuyHouse.DAL.Entities.HelperEnum
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Search</title>
	<link rel="stylesheet" href="~/css/Create-EditAdvert.css" />
</head>
<body>
	<div class="container pt-3 pb-3">
		<div class="row">
			<h1 class="main_title">@Localizer["Create your advert"]: </h1><hr />
			<div class="col-lg-7 col-12 col-xs-12 col-md-12 order-md-2 order-2 order-lg-1 form_block">
				<form method="post" asp-action="CreateAdvertPost" asp-controller="HouseAdvert" enctype="multipart/form-data">
					<h2 class="subtitle">@Localizer["MainInfo"]</h2>
					@Html.LabelFor(m => m.MainInfo.Region, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.MainInfo.Region, new { @class = "form-control input_text", required="true"})
					@Html.ValidationMessageFor(m => m.MainInfo.Region,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.MainInfo.City, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.MainInfo.City, new { @class = "form-control", @required="true"  })
					@Html.ValidationMessageFor(m => m.MainInfo.City,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.MainInfo.Street, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.MainInfo.Street, new { @class = "form-control", @required="true"  })
					@Html.ValidationMessageFor(m => m.MainInfo.Street,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.MainInfo.HouseNumber, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.MainInfo.HouseNumber, new { @class = "form-control", @required="true"  })
					@Html.ValidationMessageFor(m => m.MainInfo.HouseNumber,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.MainInfo.RegistrationDate, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.MainInfo.RegistrationDate, new { @class = "form-control", @type="date", @required="true"  })
					@Html.ValidationMessageFor(m => m.MainInfo.RegistrationDate,"", new{@class="validation_text"})<br />
					<hr />

					<h2 class="subtitle">@Localizer["Parameters"]</h2>
					@Html.LabelFor(m => m.Description, new{@class="input_lable"})
					@Html.TextAreaFor(m => m.Description, new { @class = "form-control", @required="true"  })
					@Html.ValidationMessageFor(m => m.Description,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.Type, new{@class="input_lable"})<br />
					@Html.RadioButtonFor(m => m.Type, TypeOfRealty.Primary , new{ @required="true", @class="radio_input"})
					<lable>@Localizer["Primary"]</lable><br />
					@Html.RadioButtonFor(m => m.Type, TypeOfRealty.Secondary , new{ @required="true", @class="radio_input"})
					<lable>@Localizer["Secondary"]</lable><br />
					@Html.ValidationMessageFor(m => m.Type,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.Rooms, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.Rooms, new { @class = "form-control", @type="number",  @required="true" })
					@Html.ValidationMessageFor(m => m.Rooms,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.TypeOfWalls, new{@class="input_lable"})
					<select class="form-control" name="TypeOfWalls" required>
						<option value="@TypeOfWalls.Brick">@Localizer["Brick"]</option>
						<option value="@TypeOfWalls.Frame">@Localizer["Frame"]</option>
						<option value="@TypeOfWalls.Panel">@Localizer["Panel"]</option>
						<option value="@TypeOfWalls.FoamBlock">@Localizer["FoamBlock"]</option>
						<option value="@TypeOfWalls.Ferroconcrete">@Localizer["Ferroconcrete"]</option>
						<option value="@TypeOfWalls.AeratedСoncrete">@Localizer["AeratedСoncrete"]</option>
						<option value="@TypeOfWalls.BlockBrick">@Localizer["BlockBrick"]</option>
						<option value="@TypeOfWalls.Monolith">@Localizer["Monolith"]</option>
					</select>
					@Html.ValidationMessageFor(m => m.TypeOfWalls,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.TotalArea, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.TotalArea, new { @class = "form-control", @required="true" })
					@Html.ValidationMessageFor(m => m.TotalArea,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.LivingArea, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.LivingArea, new { @class = "form-control", @required="true" })
					@Html.ValidationMessageFor(m => m.LivingArea,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.LandArea, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.LandArea, new { @class = "form-control", @required="true" })
					@Html.ValidationMessageFor(m => m.LandArea,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.TotalCountFloors, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.TotalCountFloors, new { @class = "form-control", @type="number", @required="true" })
					@Html.ValidationMessageFor(m => m.TotalCountFloors,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.Heating, new{@class="input_lable"})<br />
					@Html.RadioButtonFor(m => m.Heating,@TypeOfHeating.Centralized, new{ @required="true", @class="radio_input"})
					<lable>@Localizer["Centralized"]</lable><br />
					@Html.RadioButtonFor(m => m.Heating,@TypeOfHeating.Individual, new{ @required="true", @class="radio_input"})
					<lable>@Localizer["Individual"]</lable><br />
					@Html.RadioButtonFor(m => m.Heating,@TypeOfHeating.Сombined, new{ @required="true", @class="radio_input"})
					<lable>@Localizer["Сombined"]</lable><br />
					@Html.RadioButtonFor(m => m.Heating,@TypeOfHeating.WithoutHeating, new{ @required="true", @class="radio_input"})
					<lable>@Localizer["WithoutHeating"]</lable><br />
					@Html.ValidationMessageFor(m => m.Heating,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.YearBuilt, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.YearBuilt, new { @class = "form-control", @type="number", @step="1", @required="true" })
					@Html.ValidationMessageFor(m => m.YearBuilt,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.RegistrationNumber, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.RegistrationNumber, new { @class = "form-control", @required="true"})
					@Html.ValidationMessageFor(m => m.RegistrationNumber,"", new{@class="validation_text"})<br />

					@Html.LabelFor(m => m.CadastralNumber, new{@class="input_lable"})
					@Html.TextBoxFor(m => m.CadastralNumber, new { @class = "form-control", @required="true"})
					@Html.ValidationMessageFor(m => m.CadastralNumber,"", new{@class="validation_text"})<br />

					<div class="row">
						<div class="col-md-10">
							<lable class="input_lable">@Localizer["Price"]</lable>
							@Html.TextBoxFor(m => m.TotalPrice, new { @class = "form-control", @type="number", required="true" })
							@Html.ValidationMessageFor(m => m.TotalPrice,"", new{@class="validation_text"})<br />
						</div>
						<div class="col-md-2 mt-1">
							<lable class="input_lable">Валюта</lable>
							<select class="form-control" name="Currency" required>
								<option value="@Currency.USD">USD</option>
								<option value="@Currency.Euro">Euro</option>
								<option value="@Currency.UAH">UAH</option>
							</select>
							@Html.ValidationMessageFor(m => m.Currency,"", new{@class="validation_text"})<br />
						</div>
					</div>

					@Html.LabelFor(m => m.TypePrice, new{@class="input_lable"})<br />
					@Html.RadioButtonFor(m => m.TypePrice, TypeOfPrice.PerSquareMeter , new{ @required="true", @class="radio_input"})
					<lable>@Localizer["PricePerSquareMeter"]</lable><br />
					@Html.RadioButtonFor(m => m.TypePrice, TypeOfPrice.TotalPrice , new{ @required="true", @class="radio_input"})
					<lable>@Localizer["PricePerObject"]</lable><br />
					@Html.ValidationMessageFor(m => m.TypePrice,"", new{@class="validation_text"})<br />

					<hr />
					<h2 class="subtitle">@Localizer["Photo"]</h2>
					<p>@Localizer["Upload photos message"]</p>
					<input class="form-control" type="file" multiple name="uploads" required accept="image/jpeg,image/png" /><br>
					@Html.ValidationMessageFor(m => m.Photos,"", new{@class="validation_text"})<br />
					<button type="submit" class="btn btn-lg btn-dark">@Localizer["Create advert"]</button>
				</form>
			</div>
			<div class="col-lg-4 img_block col-md-12 order-lg-2 order-md-1 order-1 ">
			</div>
		</div>
	</div>
</body>
</html>

src/BuyHouse/BuyHouse.WEB/Views/HouseAdvert/GetHouseAdvert.cshtml
@model BuyHouse.WEB.Models.ViewModels.GetAdvertViewModel<HouseAdvertModel>
@using BuyHouse.WEB.Models.AdvertModel
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
<link rel="stylesheet" href="~/css/GetAdvert.css" />
<div class="container pt-3 pb-3">
	<div class="row">
		<div class="col-lg-8">
			<div id="carouselExampleFade" class="carousel slide carousel-fade slider_block" data-bs-ride="carousel">
				<div class="carousel-inner">
					@foreach (var photo in Model.Advert.Photos)
					{
						<div class="carousel-item active">
							<img src="@photo.Path" class="d-block slider_img">
						</div>
					}
				</div>
				<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="visually-hidden">Previous</span>
				</button>
				<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="visually-hidden">Next</span>
				</button>
			</div>
		</div>
		<div class="col-lg-4 pt-md-3 pt-sm-3 pt-3">
			<h2 class="sellerInfo_title">@Localizer["Seller info"]</h2><hr />
			<div class="row">
			<div class="col-lg-5 col-md-3 col-sm-4 col-4">
				<div class="container_avatar">
					<img src="@Model.UserProfile.UserAvatar.Path" alt="avatar" class="rounded-circle img-fluid avatar_img"/>
				</div>
			</div>
			<div class="col-lg-7 col-md-9 col-sm-8 col-8">
				<div class="pt-4">
					<h2 class="sellerInfo_title">@Model.UserProfile.Name</h2>
					<h2 class="sellerInfo_title">@Model.UserProfile.Surname</h2>
				</div>
			</div>
			</div>
			<div class="row">
				@if (Model.UserProfile.PhoneNumber != null)
				{
					<div class="phone_block">
						@Model.UserProfile.PhoneNumber.Substring(0,3) (@Model.UserProfile.PhoneNumber.Substring(3, 3))
						<span class="num_hide">@Model.UserProfile.PhoneNumber.Substring(6,3)-@Model.UserProfile.PhoneNumber.Substring(9,2)-@Model.UserProfile.PhoneNumber.Substring(11,2)</span>
						<span class="sh_nmr"> @Localizer["show"]</span>

					</div>
				}
			</div>
		</div>
	</div>
	<div class="row pt-3">
		<div class="col-lg-8 col-md-12 blue_block p-4">
			<h3 class="adress_title">@Model.Advert.MainInfo.Region, @Model.Advert.MainInfo.City, @Model.Advert.MainInfo.Street, @Model.Advert.MainInfo.HouseNumber</h3>
			<hr />
			<p class="param_block_advert">
				<img src="~/images/icons/money.png" class="mb-2" width="20" height="20" />
				<b>@Model.Advert.TotalPrice @Localizer[Model.Advert.Currency.ToString()]</b>
				@Localizer["price"] @Localizer["per object"]
				(@Model.Advert.PricePerSquareMeter @Localizer[Model.Advert.Currency.ToString()] @Localizer["per"] м<sup>2</sup>)
			</p>
			<p>
				<img src="~/images/icons/done.png" class="mb-2" width="20" height="20" />
				<b>@Localizer["Type of realty"]:</b> @Localizer[Model.Advert.Type.ToString()]
			</p>
			<p>
				<img src="~/images/icons/done.png" class="mb-2" width="20" height="20" />
				<b>@Localizer["rooms"]:</b> @Model.Advert.Rooms
			</p>
			<p>
				<img src="~/images/icons/done.png" class="mb-2" width="20" height="20" />
				<b>@Localizer["type of walls"]:</b> @Localizer[Model.Advert.TypeOfWalls.ToString()]
			</p>
			<p>
				<img src="~/images/icons/done.png" class="mb-2" width="20" height="20" />
				<b>@Localizer["total area"]:</b> @Model.Advert.TotalArea
			</p>
			<p>
				<img src="~/images/icons/done.png" class="mb-2" width="20" height="20" />
				<b>@Localizer["living area"]:</b> @Model.Advert.LivingArea
			</p>
			<p>
				<img src="~/images/icons/done.png" class="mb-2" width="20" height="20" />
				<b>@Localizer["land area"]:</b> @Model.Advert.LandArea
			</p>
			<p>
				<img src="~/images/icons/done.png" class="mb-2" width="20" height="20" />
				<b>@Localizer["floor"]:</b>  @Model.Advert.TotalCountFloors
			</p>
			<p>
				<img src="~/images/icons/done.png" class="mb-2" width="20" height="20" />
				<b>@Localizer["heating"]:</b> @Localizer[Model.Advert.Heating.ToString()]
			</p>
			<p>
				<img src="~/images/icons/done.png" class="mb-2" width="20" height="20" />
				<b>@Localizer["year built"]:</b> @Model.Advert.YearBuilt
			</p><hr />
			<p>
				<img src="~/images/icons/description.png" class="mb-2" width="20" height="20" />
				<b>@Localizer["description"]:</b> @Html.Raw(Model.Advert.Description)
			</p>
			<hr />
			<div class="row">
				<div class="col-lg-11 col-sm-9 col-xs-7">
					<p>@Localizer["date of creating advert"]: @Model.Advert.CreationDate.ToString("yyyy-MM-dd")</p>
				</div>
				<div class="col-lg-1 col-sm-3 col-xs-5 like_block">
					<img id="likeimg" src="https://cdn-icons-png.flaticon.com/512/535/535234.png" width="30" height="30">
					<div id="like_advert" class="like_count">@Model.Advert.LikeCount</div>
				</div>
			</div>
		</div>
	</div>
</div>	
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
 <script src="~/js/HidePhoneScript.js"></script>
}